version: 40.0.{build}
image: Visual Studio 2019
cache:
- Build\Debug -> Tools\deps.exe, Tools\_MakeDLL.bat, Sources\, appveyor.yml
- Build\Release -> Tools\deps.exe, Tools\_MakeDLL.bat, Sources\, appveyor.yml

environment:
  svn_url: https://svn.code.sf.net/p/caveman2cosmos/code/trunk
  svn_user: c2cappveyor
  svn_pass:
    secure: 8MBckNYRp5EVPgbGcmZ6bQ==
  release_prefix: Caveman2Cosmos
  build_dir: _build

build_script:
- cmd: >-
    call Powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%APPVEYOR_BUILD_FOLDER%\Tools\CI\fix_sources_timestamps.ps1"
    
    call "%APPVEYOR_BUILD_FOLDER%\Tools\_MakeDLL.bat" build Debug

    call "%APPVEYOR_BUILD_FOLDER%\Tools\_MakeDLL.bat" build Release

test_script:
- cmd: >-
    cd Tools

    XmlValidator.exe -a

# DISABLED: before_deploy can't access secure variables it seems
# before_deploy:
# - cmd: >-
#     call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

#     echo %secure_test%
deploy_script:
- cmd: >-
    call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

# DISABLED: this doesn't work, unauthorized
# deploy:
# - provider: GitHub
#   auth_token:
#     secure: 8q/T1sjdSGdr8NWfFwisFuaMGNT5v4fKCZiS98tDQtFhbbOu2nmPSclfRfFsDE4Y
#   artifact: $(release_prefix)-$(APPVEYOR_BUILD_VERSION).zip,$(release_prefix)-CvGameCoreDLL-$(APPVEYOR_BUILD_VERSION).zip
#   prerelease: true
#   on:
#     branch: test-deployment

notifications:
- provider: Slack
  incoming_webhook:
    secure: /rZsiy2rHhDaEh9f3Hzv6RtkcI/grO+svFlzo0AErpTBOfM0e2IDGzUVemKjvU2uQhUIL+t9TgYCItXIAcTIlAuZUgbXxJJGTQn4eJ+tkgM0Ze6dt+JSvb3H5nndmk9epWUr89PASEMdwTgw3nuJJe4f7TveskQwWbS1XNEX0lF5i/B8wj+TS5uIqZQPD/wP
  channel: github
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
